name = "van_aubel_extensions"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["VanAubelExtensions"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[lean_lib]]
name = "VanAubelExtensions"
roots = ["VanAubelExtensions"]
